### ISSUE TITLE
Purpose to make ABAPKoans for ABAP kernel below 7.4

### ISSUE THREAD

**Issue by gabbianiiii** [damir-majer/ABAPKoans#2]
I want to contribute here, developing a version of ABAPKoans for ABAP kernels, below 7.4.

**Comment by damir-majer** [comment]
Hi @pacheco7 perfect! Great to see you active here ;-)
Let us have a chat about the git Organisation for this issue....

**Comment by gabbianiiii** [comment]
Sure ;)

**Comment by damir-majer** [comment]
Yes, please go ahead! Fork the project and create Pull requests for the branch '7.02-7.31'! Thanks for the contribution!
