### ISSUE TITLE
Organize the versions in directories

### ISSUE THREAD

**Issue by gabbianiiii** [damir-majer/ABAPKoans#4]
I suggest to separate the versions of ABAPKoans in directories, e.g.: abapkoans740, abapkoans730.

**Comment by damir-majer** [comment]
Hmh, how about organizing the different versions in branches? For example the master branch stands for 7.40 and the '7.02_7.31' branch stands for versions below 7.40?

**Comment by larshp** [comment]
If installing a branch with abapGit, it will try to install and activate all code, if it contains code for both 730 and 740, users on 730 will get syntax errors for 740.

What is the most important part for this project? In my opinion it is providing a starting point for ABAP unit tests, then the internal syntax does not matter IMHO, it is a lot easier to keep a single version updated.

Just my few cents

**Comment by damir-majer** [comment]
Yes, this is an issue... but what do you think about two branches that never will be merged? 
Is it possible with this restriction to choose the master branch for 7.40 related systems and the '7.02' branch for lower stacked systems?

**Comment by larshp** [comment]
yeah, it is possible to choose the branch while cloning, or alternatively downloading the zip for a specific branch in an offline scenario

downside is maintaining multiple versions

**Comment by damir-majer** [comment]
I´d created the additional branch '7.02-7.31' which contains the version for this system requirements.
